# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kookyleo"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kookyleo"
    commit-message:
      prefix: "ci"
      include: "scope"